---
services:
  debian:
    build: .
    image: dl_debian
    container_name: dl_debian
    hostname: dl_debian
    network_mode: host
    volumes:
      - ./data:/data
    command: ""
    privileged: True
    restart: unless-stopped
